services:
  api:
    image: ruby:3.3.0
    container_name: rebase_api
    working_dir: /app
    environment:
      REDIS_URL: redis://rebase_redis:6379
      TABLE_NAME: medical_exams
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -c 'bundle install --without test && ruby db/db_init.rb && ruby api/server.rb'
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: railsdbmigrate
      POSTGRES_DB: labsdb

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: rebase_webapp
    ports:
      - "1234:1234"
    volumes:
      - ./webapp:/app
    depends_on:
      - api

  sidekiq:
    image: ruby:3.3.0
    container_name: rebase_sidekiq
    working_dir: /app
    environment:
      REDIS_URL: redis://rebase_redis:6379
    command: bash -c 'bundle install && bundle exec sidekiq -r ./sidekiq/*.rb'
    volumes:
      - .:/app
    depends_on:
      - redis
      - api

  redis:
    image: redis:latest
    container_name: rebase_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - .:/app

  test:
    image: ruby:3.3.0
    container_name: rebase_test
    working_dir: /app
    environment:
      RACK_ENV: test
      REDIS_URL: redis://rebase_redis:6379
      TABLE_NAME: medical_exams_test
    volumes:
      - .:/app
    command: bash -c 'bundle install && bundle exec rspec'
    depends_on:
      - api
