# Use the official Node.js image.
FROM node:latest

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache.
COPY webapp/package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application files.
COPY webapp/ .

# Command to run the app.
CMD ["npm", "start"]